

set_property PACKAGE_PIN Y18 [get_ports {SLOT_A[0]}]
set_property PACKAGE_PIN Y19 [get_ports {SLOT_A[1]}]
set_property PACKAGE_PIN R16 [get_ports {SLOT_A[2]}]
set_property PACKAGE_PIN R17 [get_ports {SLOT_A[3]}]
set_property PACKAGE_PIN V20 [get_ports {SLOT_A[4]}]
set_property PACKAGE_PIN W20 [get_ports {SLOT_A[5]}]
set_property PACKAGE_PIN V16 [get_ports {SLOT_A[6]}]
set_property PACKAGE_PIN W16 [get_ports {SLOT_A[7]}]
set_property PACKAGE_PIN T17 [get_ports {SLOT_A[8]}]
set_property PACKAGE_PIN R18 [get_ports {SLOT_A[9]}]
set_property PACKAGE_PIN N20 [get_ports {SLOT_A[10]}]
set_property PACKAGE_PIN P20 [get_ports {SLOT_A[11]}]
set_property PACKAGE_PIN U18 [get_ports {SLOT_A[12]}]
set_property PACKAGE_PIN U19 [get_ports {SLOT_A[13]}]
set_property PACKAGE_PIN T20 [get_ports {SLOT_A[14]}]
set_property PACKAGE_PIN U20 [get_ports {SLOT_A[15]}]
set_property PACKAGE_PIN N18 [get_ports {SLOT_A[16]}]
set_property PACKAGE_PIN P19 [get_ports {SLOT_A[17]}]
set_property PACKAGE_PIN T16 [get_ports {SLOT_A[18]}]
set_property PACKAGE_PIN U17 [get_ports {SLOT_A[19]}]
set_property PACKAGE_PIN M14 [get_ports {SLOT_A[20]}]
set_property PACKAGE_PIN M15 [get_ports {SLOT_A[21]}]

set_property PACKAGE_PIN V12 [get_ports {SLOT_B[0]}]
set_property PACKAGE_PIN W13 [get_ports {SLOT_B[1]}]
set_property PACKAGE_PIN T14 [get_ports {SLOT_B[2]}]
set_property PACKAGE_PIN T15 [get_ports {SLOT_B[3]}]
set_property PACKAGE_PIN P14 [get_ports {SLOT_B[4]}]
set_property PACKAGE_PIN R14 [get_ports {SLOT_B[5]}]
set_property PACKAGE_PIN Y16 [get_ports {SLOT_B[6]}]
set_property PACKAGE_PIN Y17 [get_ports {SLOT_B[7]}]
set_property PACKAGE_PIN W14 [get_ports {SLOT_B[8]}]
set_property PACKAGE_PIN Y14 [get_ports {SLOT_B[9]}]
set_property PACKAGE_PIN U13 [get_ports {SLOT_B[10]}]
set_property PACKAGE_PIN V13 [get_ports {SLOT_B[11]}]
set_property PACKAGE_PIN T12 [get_ports {SLOT_B[12]}]
set_property PACKAGE_PIN U12 [get_ports {SLOT_B[13]}]
set_property PACKAGE_PIN T11 [get_ports {SLOT_B[14]}]
set_property PACKAGE_PIN T10 [get_ports {SLOT_B[15]}]
set_property PACKAGE_PIN V8 [get_ports {SLOT_B[16]}]
set_property PACKAGE_PIN W8 [get_ports {SLOT_B[17]}]
set_property PACKAGE_PIN V11 [get_ports {SLOT_B[18]}]
set_property PACKAGE_PIN V10 [get_ports {SLOT_B[19]}]
set_property PACKAGE_PIN G17 [get_ports {SLOT_B[20]}]
set_property PACKAGE_PIN G18 [get_ports {SLOT_B[21]}]

set_property PACKAGE_PIN J18 [get_ports {SLOT_C[0]}]
set_property PACKAGE_PIN H18 [get_ports {SLOT_C[1]}]
set_property PACKAGE_PIN K17 [get_ports {SLOT_C[2]}]
set_property PACKAGE_PIN K18 [get_ports {SLOT_C[3]}]
set_property PACKAGE_PIN K19 [get_ports {SLOT_C[4]}]
set_property PACKAGE_PIN J19 [get_ports {SLOT_C[5]}]
set_property PACKAGE_PIN M17 [get_ports {SLOT_C[6]}]
set_property PACKAGE_PIN M18 [get_ports {SLOT_C[7]}]
set_property PACKAGE_PIN F16 [get_ports {SLOT_C[8]}]
set_property PACKAGE_PIN F17 [get_ports {SLOT_C[9]}]
set_property PACKAGE_PIN M19 [get_ports {SLOT_C[10]}]
set_property PACKAGE_PIN M20 [get_ports {SLOT_C[11]}]
set_property PACKAGE_PIN E18 [get_ports {SLOT_C[12]}]
set_property PACKAGE_PIN E19 [get_ports {SLOT_C[13]}]
set_property PACKAGE_PIN E17 [get_ports {SLOT_C[14]}]
set_property PACKAGE_PIN D18 [get_ports {SLOT_C[15]}]
set_property PACKAGE_PIN C20 [get_ports {SLOT_C[16]}]
set_property PACKAGE_PIN B20 [get_ports {SLOT_C[17]}]
set_property PACKAGE_PIN B19 [get_ports {SLOT_C[18]}]
set_property PACKAGE_PIN A20 [get_ports {SLOT_C[19]}]
set_property PACKAGE_PIN D19 [get_ports {SLOT_C[20]}]
set_property PACKAGE_PIN D20 [get_ports {SLOT_C[21]}]

set_property PACKAGE_PIN U14 [get_ports {SLOT_D[0]}]
set_property PACKAGE_PIN U15 [get_ports {SLOT_D[1]}]
set_property PACKAGE_PIN Y9 [get_ports {SLOT_D[2]}]
set_property PACKAGE_PIN Y8 [get_ports {SLOT_D[3]}]
set_property PACKAGE_PIN Y7 [get_ports {SLOT_D[4]}]
set_property PACKAGE_PIN Y6 [get_ports {SLOT_D[5]}]
set_property PACKAGE_PIN T9 [get_ports {SLOT_D[6]}]
set_property PACKAGE_PIN U10 [get_ports {SLOT_D[7]}]
set_property PACKAGE_PIN U7 [get_ports {SLOT_D[8]}]
set_property PACKAGE_PIN V7 [get_ports {SLOT_D[9]}]
set_property PACKAGE_PIN J20 [get_ports {SLOT_D[10]}]
set_property PACKAGE_PIN H20 [get_ports {SLOT_D[11]}]
set_property PACKAGE_PIN G19 [get_ports {SLOT_D[12]}]
set_property PACKAGE_PIN G20 [get_ports {SLOT_D[13]}]
set_property PACKAGE_PIN F19 [get_ports {SLOT_D[14]}]
set_property PACKAGE_PIN F20 [get_ports {SLOT_D[15]}]
set_property PACKAGE_PIN H16 [get_ports {SLOT_D[16]}]
set_property PACKAGE_PIN H17 [get_ports {SLOT_D[17]}]
set_property PACKAGE_PIN L16 [get_ports {SLOT_D[18]}]
set_property PACKAGE_PIN L17 [get_ports {SLOT_D[19]}]
set_property PACKAGE_PIN L19 [get_ports {SLOT_D[20]}]
set_property PACKAGE_PIN L20 [get_ports {SLOT_D[21]}]

set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_A[21]}]

set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_B[21]}]

set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_C[21]}]

set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_D[21]}]


# led pins overlap with slots
# set_property PACKAGE_PIN R14 [get_ports {RGB_LED[0]}]
# set_property PACKAGE_PIN Y16 [get_ports {RGB_LED[1]}]
# set_property PACKAGE_PIN Y17 [get_ports {RGB_LED[2]}]

# not implemented yet
# set_property PACKAGE_PIN R19 [get_ports {USER_SW[0]}]
# set_property PACKAGE_PIN T19 [get_ports {USER_SW[1]}]
# set_property PACKAGE_PIN G14 [get_ports {USER_SW[2]}]
# set_property PACKAGE_PIN J15 [get_ports {USER_SW[3]}]

# set_property IOSTANDARD LVCMOS33 [get_ports {RGB_LED[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {RGB_LED[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {RGB_LED[2]}]

set_property PACKAGE_PIN P18 [get_ports {BUZZER}]

set_property IOSTANDARD LVCMOS33 [get_ports {BUZZER}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

