/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post99, git sha1 a1bb0255d) */

(* top =  1  *)
(* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:167" *)
(* generator = "Amaranth" *)
module controller(ARESETN, AWID, AWADDR, AWLEN, AWSIZE, AWBURST, AWLOCK, AWCACHE, AWPROT, AWREGION, AWQOS, AWUSER, AWVALID, WID, WDATA, WSTRB, WLAST, WUSER, WVALID, BREADY, ARID
, ARADDR, ARLEN, ARSIZE, ARBURST, ARLOCK, ARCACHE, ARPROT, ARREGION, ARQOS, ARUSER, ARVALID, RREADY, AWREADY, WREADY, BID, BRESP, BUSER, BVALID, ARREADY, RID, RDATA
, RRESP, RLAST, RUSER, RVALID, ACLK);
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 AXI CLK" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME AXI, CLK_DOMAIN clk_domain, FREQ_HZ 100000000, PHASE 0.0, PROTOCOL AXI4, DATA_WIDTH 32, ID_WIDTH 4, ADDR_WIDTH 16, HAS_BURST 1, HAS_CACHE 1, HAS_LOCK 1, HAS_PROT 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, READ_WRITE_MODE READ_WRITE" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:170" *)
  input ACLK;
  wire ACLK;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARADDR" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:88" *)
  input [15:0] ARADDR;
  wire [15:0] ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARBURST" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:91" *)
  input [1:0] ARBURST;
  wire [1:0] ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARCACHE" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:93" *)
  input [3:0] ARCACHE;
  wire [3:0] ARCACHE;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 AXI RST" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:53" *)
  input ARESETN;
  wire ARESETN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:87" *)
  input [3:0] ARID;
  wire [3:0] ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARLEN" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:89" *)
  input [7:0] ARLEN;
  wire [7:0] ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARLOCK" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:92" *)
  input ARLOCK;
  wire ARLOCK;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARPROT" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:94" *)
  input [2:0] ARPROT;
  wire [2:0] ARPROT;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARQOS" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:96" *)
  input [3:0] ARQOS;
  wire [3:0] ARQOS;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:107" *)
  output ARREADY;
  wire ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARREGION" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:95" *)
  input [3:0] ARREGION;
  wire [3:0] ARREGION;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARSIZE" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:90" *)
  input [2:0] ARSIZE;
  wire [2:0] ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARUSER" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:97" *)
  input ARUSER;
  wire ARUSER;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI ARVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:98" *)
  input ARVALID;
  wire ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWADDR" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:57" *)
  input [15:0] AWADDR;
  wire [15:0] AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWBURST" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:60" *)
  input [1:0] AWBURST;
  wire [1:0] AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWCACHE" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:62" *)
  input [3:0] AWCACHE;
  wire [3:0] AWCACHE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:56" *)
  input [3:0] AWID;
  wire [3:0] AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWLEN" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:58" *)
  input [7:0] AWLEN;
  wire [7:0] AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWLOCK" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:61" *)
  input AWLOCK;
  wire AWLOCK;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWPROT" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:63" *)
  input [2:0] AWPROT;
  wire [2:0] AWPROT;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWQOS" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:65" *)
  input [3:0] AWQOS;
  wire [3:0] AWQOS;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:107" *)
  output AWREADY;
  wire AWREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWREGION" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:64" *)
  input [3:0] AWREGION;
  wire [3:0] AWREGION;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWSIZE" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:59" *)
  input [2:0] AWSIZE;
  wire [2:0] AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWUSER" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:66" *)
  input AWUSER;
  wire AWUSER;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI AWVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:67" *)
  input AWVALID;
  wire AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:102" *)
  output [3:0] BID;
  wire [3:0] BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI BREADY" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:84" *)
  input BREADY;
  wire BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RRESP" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:104" *)
  output [1:0] BRESP;
  wire [1:0] BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:107" *)
  output BUSER;
  wire BUSER;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:107" *)
  output BVALID;
  wire BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RDATA" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:103" *)
  output [31:0] RDATA;
  wire [31:0] RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:102" *)
  output [3:0] RID;
  wire [3:0] RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:107" *)
  output RLAST;
  wire RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RREADY" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:108" *)
  input RREADY;
  wire RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RRESP" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:104" *)
  output [1:0] RRESP;
  wire [1:0] RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:107" *)
  output RUSER;
  wire RUSER;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:107" *)
  output RVALID;
  wire RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI WDATA" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:72" *)
  input [31:0] WDATA;
  wire [31:0] WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI WID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:71" *)
  input [3:0] WID;
  wire [3:0] WID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI WLAST" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:74" *)
  input WLAST;
  wire WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI RVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:107" *)
  output WREADY;
  wire WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI WSTRB" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:73" *)
  input [3:0] WSTRB;
  wire [3:0] WSTRB;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI WUSER" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:75" *)
  input WUSER;
  wire WUSER;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 AXI WVALID" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:76" *)
  input WVALID;
  wire WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 AXI CLK" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME AXI, CLK_DOMAIN clk_domain, FREQ_HZ 100000000, PHASE 0.0, PROTOCOL AXI4, DATA_WIDTH 32, ID_WIDTH 4, ADDR_WIDTH 16, HAS_BURST 1, HAS_CACHE 1, HAS_LOCK 1, HAS_PROT 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, READ_WRITE_MODE READ_WRITE" *)
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:170" *)
  wire clk;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:170" *)
  wire rst;
  assign rst = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\src\\axi.py:173" *) ARESETN;
  assign clk = ACLK;
  assign AWREADY = 1'h0;
  assign WREADY = 1'h0;
  assign BID = 4'h0;
  assign BRESP = 2'h0;
  assign BUSER = 1'h0;
  assign BVALID = 1'h0;
  assign ARREADY = 1'h0;
  assign RID = 4'h0;
  assign RDATA = 32'd0;
  assign RRESP = 2'h0;
  assign RLAST = 1'h0;
  assign RUSER = 1'h0;
  assign RVALID = 1'h0;
endmodule
