/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post98, git sha1 a1bb0255d) */

(* top =  1  *)
(* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:19" *)
(* generator = "Amaranth" *)
module counter(clk, rst, output_, output_compare);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire \$1 ;
  wire [16:0] \$2 ;
  wire [16:0] \$3 ;
  wire \$4 ;
  wire \$5 ;
  reg \$6 ;
  reg [15:0] \$7 ;
  reg \$8 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\lib\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:21" *)
  reg [15:0] counter = 16'h0000;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:22" *)
  reg dir = 1'h1;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:16" *)
  output output_;
  reg output_ = 1'h0;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:15" *)
  input [15:0] output_compare;
  wire [15:0] output_compare;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\lib\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input rst;
  wire rst;
  assign \$2  = counter + (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:31" *) 1'h1;
  assign \$3  = counter - (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:33" *) 1'h1;
  assign \$4  = counter == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:36" *) 16'hfffe;
  assign \$5  = counter == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:40" *) 1'h1;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:16" *)
  always @(posedge clk)
    output_ <= \$6 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:21" *)
  always @(posedge clk)
    counter <= \$7 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:22" *)
  always @(posedge clk)
    dir <= \$8 ;
  assign \$1  = output_compare > (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\amaranth_sources\\counter.py:24" *) counter;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$6  = 1'h1;
    end else begin
      \$6  = 1'h0;
    end
    if (rst) begin
      \$6  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (dir) begin
      \$7  = \$2 [15:0];
    end else begin
      \$7  = \$3 [15:0];
    end
    if (rst) begin
      \$7  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$8  = dir;
    if (\$4 ) begin
      \$8  = 1'h0;
    end
    if (\$5 ) begin
      \$8  = 1'h1;
    end
    if (rst) begin
      \$8  = 1'h1;
    end
  end
endmodule
