/* Generated by Amaranth Yosys 0.35 (PyPI ver 0.35.0.0.post81, git sha1 cc31c6ebc) */

(* top =  1  *)
(* generator = "Amaranth" *)
module fanucEncoder(tx, rx, rxData, rxDone, clk, rst, txStart);
  reg \$auto$verilog_backend.cc:2189:dump_module$1  = 0;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:415" *)
  wire \$1 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:418" *)
  wire \$10 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$100 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
  wire \$102 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$104 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$106 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
  wire \$108 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
  wire \$110 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$112 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$114 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
  wire \$116 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:480" *)
  wire [6:0] \$118 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:480" *)
  wire [6:0] \$119 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:418" *)
  wire \$12 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$121 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$123 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$125 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$127 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$129 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$131 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$133 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
  wire \$135 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
  wire \$137 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$139 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:418" *)
  wire \$14 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$141 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
  wire \$143 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:471" *)
  wire [8:0] \$145 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:471" *)
  wire [8:0] \$146 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
  wire \$148 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
  wire \$150 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$152 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$154 ;
  reg \$156 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
  wire \$157 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
  wire \$159 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:419" *)
  wire [3:0] \$16 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$161 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$163 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:419" *)
  wire [3:0] \$17 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:421" *)
  wire \$19 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:424" *)
  wire \$21 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$23 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$25 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" *)
  wire \$27 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" *)
  wire \$29 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:415" *)
  wire \$3 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:448" *)
  wire \$31 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:448" *)
  wire \$33 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:448" *)
  wire \$35 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$37 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$39 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" *)
  wire \$41 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" *)
  wire \$43 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:446" *)
  wire [9:0] \$45 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:446" *)
  wire [9:0] \$46 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$48 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:415" *)
  wire \$5 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$50 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" *)
  wire \$52 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" *)
  wire \$54 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
  wire \$56 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
  wire \$58 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$60 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$62 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
  wire \$64 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$66 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$68 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:416" *)
  wire [3:0] \$7 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$70 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$72 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$74 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$76 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
  wire \$78 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:416" *)
  wire [3:0] \$8 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
  wire \$80 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
  wire \$82 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$84 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$86 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
  wire \$88 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$90 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
  wire \$92 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
  wire \$94 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
  wire \$96 ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *)
  wire \$98 ;
  (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\ir.py:508" *)
  input clk;
  wire clk;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:409" *)
  reg [2:0] debounceCounter = 3'h0;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:409" *)
  reg [2:0] \debounceCounter$next ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:410" *)
  reg debouncedRx = 1'h0;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:410" *)
  reg \debouncedRx$next ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:412" *)
  reg oldRxLevel = 1'h1;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:412" *)
  reg \oldRxLevel$next ;
  (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\ir.py:508" *)
  input rst;
  wire rst;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:379" *)
  input rx;
  wire rx;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:406" *)
  reg [7:0] rxCurrentBit = 8'h00;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:406" *)
  reg [7:0] \rxCurrentBit$next ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:384" *)
  output [127:0] rxData;
  reg [127:0] rxData = 128'h00000000000000000000000000000000;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:384" *)
  reg [127:0] \rxData$next ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:385" *)
  output rxDone;
  reg rxDone = 1'h1;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:385" *)
  reg \rxDone$next ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:405" *)
  reg rxState = 1'h0;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:405" *)
  reg \rxState$next ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:404" *)
  reg [5:0] rxTimer = 6'h00;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:404" *)
  reg [5:0] \rxTimer$next ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:380" *)
  output tx;
  reg tx = 1'h0;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:380" *)
  reg \tx$next ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:377" *)
  input txStart;
  wire txStart;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:402" *)
  reg [1:0] txState = 2'h0;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:402" *)
  reg [1:0] \txState$next ;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:401" *)
  reg [8:0] txTimer = 9'h000;
  (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:401" *)
  reg [8:0] \txTimer$next ;
  assign \$100  = debouncedRx == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) \$98 ;
  assign \$102  = rxCurrentBit >= (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *) 7'h4c;
  assign \$104  = txState != (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) 2'h1;
  assign \$106  = txStart & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) \$104 ;
  assign \$10  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:418" *) rx;
  assign \$110  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *) rxTimer;
  assign \$112  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) oldRxLevel;
  assign \$114  = debouncedRx == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) \$112 ;
  assign \$116  = rxCurrentBit >= (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *) 7'h4c;
  assign \$119  = rxTimer - (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:480" *) 1'h1;
  assign \$121  = txState != (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) 2'h1;
  assign \$123  = txStart & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) \$121 ;
  assign \$125  = txState == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *) 2'h2;
  assign \$127  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *) rxState;
  assign \$12  = debounceCounter > (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:418" *) 1'h0;
  assign \$131  = \$127  & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *) \$129 ;
  assign \$133  = \$125  & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *) \$131 ;
  assign \$137  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *) rxTimer;
  assign \$139  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) oldRxLevel;
  assign \$141  = debouncedRx == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) \$139 ;
  assign \$143  = rxCurrentBit >= (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *) 7'h4c;
  assign \$146  = rxCurrentBit + (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:471" *) 1'h1;
  assign \$14  = \$10  & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:418" *) \$12 ;
  assign \$150  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *) rxTimer;
  assign \$152  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) oldRxLevel;
  assign \$154  = debouncedRx == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) \$152 ;
  assign \$159  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *) rxTimer;
  assign \$161  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) oldRxLevel;
  assign \$163  = debouncedRx == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) \$161 ;
  always @(posedge clk)
    debounceCounter <= \debounceCounter$next ;
  always @(posedge clk)
    debouncedRx <= \debouncedRx$next ;
  always @(posedge clk)
    tx <= \tx$next ;
  always @(posedge clk)
    txTimer <= \txTimer$next ;
  always @(posedge clk)
    txState <= \txState$next ;
  always @(posedge clk)
    rxState <= \rxState$next ;
  always @(posedge clk)
    rxDone <= \rxDone$next ;
  always @(posedge clk)
    rxTimer <= \rxTimer$next ;
  always @(posedge clk)
    rxCurrentBit <= \rxCurrentBit$next ;
  always @(posedge clk)
    rxData <= \rxData$next ;
  always @(posedge clk)
    oldRxLevel <= \oldRxLevel$next ;
  assign \$17  = debounceCounter - (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:419" *) 1'h1;
  assign \$19  = debounceCounter == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:421" *) 3'h5;
  assign \$21  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:424" *) debounceCounter;
  assign \$23  = txState != (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) 2'h1;
  assign \$25  = txStart & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) \$23 ;
  assign \$27  = txState == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" *) 2'h1;
  assign \$29  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" *) txTimer;
  assign \$31  = txState == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:448" *) 2'h2;
  assign \$33  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:448" *) txState;
  assign \$35  = \$31  | (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:448" *) \$33 ;
  assign \$37  = txState != (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) 2'h1;
  assign \$3  = debounceCounter < (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:415" *) 3'h5;
  assign \$39  = txStart & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) \$37 ;
  assign \$41  = txState == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" *) 2'h1;
  assign \$43  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" *) txTimer;
  assign \$46  = txTimer - (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:446" *) 1'h1;
  assign \$48  = txState != (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) 2'h1;
  assign \$50  = txStart & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) \$48 ;
  assign \$52  = txState == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" *) 2'h1;
  assign \$54  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" *) txTimer;
  assign \$58  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *) rxTimer;
  assign \$5  = \$1  & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:415" *) \$3 ;
  assign \$60  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) oldRxLevel;
  assign \$62  = debouncedRx == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) \$60 ;
  assign \$64  = rxCurrentBit >= (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *) 7'h4c;
  assign \$66  = txState != (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) 2'h1;
  assign \$68  = txStart & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) \$66 ;
  assign \$70  = txState == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *) 2'h2;
  assign \$72  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *) rxState;
  assign \$76  = \$72  & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *) \$74 ;
  assign \$78  = \$70  & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *) \$76 ;
  assign \$82  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *) rxTimer;
  assign \$84  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) oldRxLevel;
  assign \$86  = debouncedRx == (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) \$84 ;
  assign \$88  = rxCurrentBit >= (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *) 7'h4c;
  assign \$8  = debounceCounter + (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:416" *) 1'h1;
  assign \$90  = txState != (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) 2'h1;
  assign \$92  = txStart & (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *) \$90 ;
  assign \$96  = ! (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *) rxTimer;
  assign \$98  = ~ (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" *) oldRxLevel;
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \debounceCounter$next  = debounceCounter;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:415" *)
    casez (\$5 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:415" */
      1'h1:
          \debounceCounter$next  = \$8 [2:0];
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:418" *)
    casez (\$14 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:418" */
      1'h1:
          \debounceCounter$next  = \$17 [2:0];
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \debounceCounter$next  = 3'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \debouncedRx$next  = debouncedRx;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:421" *)
    casez (\$19 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:421" */
      1'h1:
          \debouncedRx$next  = 1'h1;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:424" *)
    casez (\$21 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:424" */
      1'h1:
          \debouncedRx$next  = 1'h0;
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \debouncedRx$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \oldRxLevel$next  = oldRxLevel;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
    casez (\$157 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" */
      1'h1:
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
          casez ({ \$163 , \$159  })
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" */
            2'b?1:
                /* empty */;
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" */
            2'b1?:
                \oldRxLevel$next  = debouncedRx;
          endcase
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \oldRxLevel$next  = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \tx$next  = tx;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
    casez (\$25 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" */
      1'h1:
          \tx$next  = 1'h1;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" *)
    casez (\$27 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" */
      1'h1:
        begin
          \tx$next  = 1'h1;
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" *)
          casez (\$29 )
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" */
            1'h1:
                \tx$next  = 1'h0;
          endcase
        end
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:448" *)
    casez (\$35 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:448" */
      1'h1:
          \tx$next  = 1'h0;
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \tx$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \txTimer$next  = txTimer;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
    casez (\$39 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" */
      1'h1:
          \txTimer$next  = 9'h190;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" *)
    casez (\$41 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" *)
          casez (\$43 )
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" */
            1'h1:
                /* empty */;
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:445" */
            default:
                \txTimer$next  = \$46 [8:0];
          endcase
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \txTimer$next  = 9'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \txState$next  = txState;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
    casez (\$50 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" */
      1'h1:
          \txState$next  = 2'h1;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" *)
    casez (\$52 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:440" */
      1'h1:
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" *)
          casez (\$54 )
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:442" */
            1'h1:
                \txState$next  = 2'h2;
          endcase
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
    casez (\$56 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" */
      1'h1:
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
          casez ({ \$62 , \$58  })
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" */
            2'b?1:
                (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
                casez (\$64 )
                  /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" */
                  1'h1:
                      \txState$next  = 2'h0;
                endcase
          endcase
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \txState$next  = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \rxState$next  = rxState;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
    casez (\$68 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" */
      1'h1:
          \rxState$next  = 1'h0;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
    casez (\$78 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" */
      1'h1:
          \rxState$next  = 1'h1;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
    casez (\$80 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" */
      1'h1:
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
          casez ({ \$86 , \$82  })
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" */
            2'b?1:
                (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
                casez (\$88 )
                  /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" */
                  1'h1:
                      \rxState$next  = 1'h0;
                endcase
          endcase
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \rxState$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \rxDone$next  = rxDone;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
    casez (\$92 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" */
      1'h1:
          \rxDone$next  = 1'h0;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
    casez (\$94 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" */
      1'h1:
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
          casez ({ \$100 , \$96  })
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" */
            2'b?1:
                (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
                casez (\$102 )
                  /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" */
                  1'h1:
                      \rxDone$next  = 1'h1;
                endcase
          endcase
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \rxDone$next  = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \rxTimer$next  = rxTimer;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
    casez (\$106 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" */
      1'h1:
          \rxTimer$next  = 6'h16;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
    casez (\$108 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
          casez ({ \$114 , \$110  })
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" */
            2'b?1:
                (* full_case = 32'd1 *)
                (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
                casez (\$116 )
                  /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" */
                  1'h1:
                      /* empty */;
                  /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:470" */
                  default:
                      \rxTimer$next  = 6'h2f;
                endcase
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:475" */
            2'b1?:
                \rxTimer$next  = 6'h16;
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:479" */
            default:
                \rxTimer$next  = \$119 [5:0];
          endcase
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \rxTimer$next  = 6'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \rxCurrentBit$next  = rxCurrentBit;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" *)
    casez (\$123 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:429" */
      1'h1:
          \rxCurrentBit$next  = 8'h00;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" *)
    casez (\$133 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:452" */
      1'h1:
          \rxCurrentBit$next  = 8'h00;
    endcase
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
    casez (\$135 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" */
      1'h1:
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
          casez ({ \$141 , \$137  })
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" */
            2'b?1:
                (* full_case = 32'd1 *)
                (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" *)
                casez (\$143 )
                  /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:465" */
                  1'h1:
                      /* empty */;
                  /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:470" */
                  default:
                      \rxCurrentBit$next  = \$146 [7:0];
                endcase
          endcase
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \rxCurrentBit$next  = 8'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \rxData$next  = rxData;
    (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" *)
    casez (\$148 )
      /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:458" */
      1'h1:
          (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" *)
          casez ({ \$154 , \$150  })
            /* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:461" */
            2'b?1:
                (* full_case = 32'd1 *)
                (* src = "c:\\Users\\voids\\Documents\\GitHub\\controller-software\\controller-firmware\\python\\test.py:463" *)
                casez (rxCurrentBit)
                  8'h00:
                      \rxData$next [0] = debouncedRx;
                  8'h01:
                      \rxData$next [1] = debouncedRx;
                  8'h02:
                      \rxData$next [2] = debouncedRx;
                  8'h03:
                      \rxData$next [3] = debouncedRx;
                  8'h04:
                      \rxData$next [4] = debouncedRx;
                  8'h05:
                      \rxData$next [5] = debouncedRx;
                  8'h06:
                      \rxData$next [6] = debouncedRx;
                  8'h07:
                      \rxData$next [7] = debouncedRx;
                  8'h08:
                      \rxData$next [8] = debouncedRx;
                  8'h09:
                      \rxData$next [9] = debouncedRx;
                  8'h0a:
                      \rxData$next [10] = debouncedRx;
                  8'h0b:
                      \rxData$next [11] = debouncedRx;
                  8'h0c:
                      \rxData$next [12] = debouncedRx;
                  8'h0d:
                      \rxData$next [13] = debouncedRx;
                  8'h0e:
                      \rxData$next [14] = debouncedRx;
                  8'h0f:
                      \rxData$next [15] = debouncedRx;
                  8'h10:
                      \rxData$next [16] = debouncedRx;
                  8'h11:
                      \rxData$next [17] = debouncedRx;
                  8'h12:
                      \rxData$next [18] = debouncedRx;
                  8'h13:
                      \rxData$next [19] = debouncedRx;
                  8'h14:
                      \rxData$next [20] = debouncedRx;
                  8'h15:
                      \rxData$next [21] = debouncedRx;
                  8'h16:
                      \rxData$next [22] = debouncedRx;
                  8'h17:
                      \rxData$next [23] = debouncedRx;
                  8'h18:
                      \rxData$next [24] = debouncedRx;
                  8'h19:
                      \rxData$next [25] = debouncedRx;
                  8'h1a:
                      \rxData$next [26] = debouncedRx;
                  8'h1b:
                      \rxData$next [27] = debouncedRx;
                  8'h1c:
                      \rxData$next [28] = debouncedRx;
                  8'h1d:
                      \rxData$next [29] = debouncedRx;
                  8'h1e:
                      \rxData$next [30] = debouncedRx;
                  8'h1f:
                      \rxData$next [31] = debouncedRx;
                  8'h20:
                      \rxData$next [32] = debouncedRx;
                  8'h21:
                      \rxData$next [33] = debouncedRx;
                  8'h22:
                      \rxData$next [34] = debouncedRx;
                  8'h23:
                      \rxData$next [35] = debouncedRx;
                  8'h24:
                      \rxData$next [36] = debouncedRx;
                  8'h25:
                      \rxData$next [37] = debouncedRx;
                  8'h26:
                      \rxData$next [38] = debouncedRx;
                  8'h27:
                      \rxData$next [39] = debouncedRx;
                  8'h28:
                      \rxData$next [40] = debouncedRx;
                  8'h29:
                      \rxData$next [41] = debouncedRx;
                  8'h2a:
                      \rxData$next [42] = debouncedRx;
                  8'h2b:
                      \rxData$next [43] = debouncedRx;
                  8'h2c:
                      \rxData$next [44] = debouncedRx;
                  8'h2d:
                      \rxData$next [45] = debouncedRx;
                  8'h2e:
                      \rxData$next [46] = debouncedRx;
                  8'h2f:
                      \rxData$next [47] = debouncedRx;
                  8'h30:
                      \rxData$next [48] = debouncedRx;
                  8'h31:
                      \rxData$next [49] = debouncedRx;
                  8'h32:
                      \rxData$next [50] = debouncedRx;
                  8'h33:
                      \rxData$next [51] = debouncedRx;
                  8'h34:
                      \rxData$next [52] = debouncedRx;
                  8'h35:
                      \rxData$next [53] = debouncedRx;
                  8'h36:
                      \rxData$next [54] = debouncedRx;
                  8'h37:
                      \rxData$next [55] = debouncedRx;
                  8'h38:
                      \rxData$next [56] = debouncedRx;
                  8'h39:
                      \rxData$next [57] = debouncedRx;
                  8'h3a:
                      \rxData$next [58] = debouncedRx;
                  8'h3b:
                      \rxData$next [59] = debouncedRx;
                  8'h3c:
                      \rxData$next [60] = debouncedRx;
                  8'h3d:
                      \rxData$next [61] = debouncedRx;
                  8'h3e:
                      \rxData$next [62] = debouncedRx;
                  8'h3f:
                      \rxData$next [63] = debouncedRx;
                  8'h40:
                      \rxData$next [64] = debouncedRx;
                  8'h41:
                      \rxData$next [65] = debouncedRx;
                  8'h42:
                      \rxData$next [66] = debouncedRx;
                  8'h43:
                      \rxData$next [67] = debouncedRx;
                  8'h44:
                      \rxData$next [68] = debouncedRx;
                  8'h45:
                      \rxData$next [69] = debouncedRx;
                  8'h46:
                      \rxData$next [70] = debouncedRx;
                  8'h47:
                      \rxData$next [71] = debouncedRx;
                  8'h48:
                      \rxData$next [72] = debouncedRx;
                  8'h49:
                      \rxData$next [73] = debouncedRx;
                  8'h4a:
                      \rxData$next [74] = debouncedRx;
                  8'h4b:
                      \rxData$next [75] = debouncedRx;
                  8'h4c:
                      \rxData$next [76] = debouncedRx;
                  8'h4d:
                      \rxData$next [77] = debouncedRx;
                  8'h4e:
                      \rxData$next [78] = debouncedRx;
                  8'h4f:
                      \rxData$next [79] = debouncedRx;
                  8'h50:
                      \rxData$next [80] = debouncedRx;
                  8'h51:
                      \rxData$next [81] = debouncedRx;
                  8'h52:
                      \rxData$next [82] = debouncedRx;
                  8'h53:
                      \rxData$next [83] = debouncedRx;
                  8'h54:
                      \rxData$next [84] = debouncedRx;
                  8'h55:
                      \rxData$next [85] = debouncedRx;
                  8'h56:
                      \rxData$next [86] = debouncedRx;
                  8'h57:
                      \rxData$next [87] = debouncedRx;
                  8'h58:
                      \rxData$next [88] = debouncedRx;
                  8'h59:
                      \rxData$next [89] = debouncedRx;
                  8'h5a:
                      \rxData$next [90] = debouncedRx;
                  8'h5b:
                      \rxData$next [91] = debouncedRx;
                  8'h5c:
                      \rxData$next [92] = debouncedRx;
                  8'h5d:
                      \rxData$next [93] = debouncedRx;
                  8'h5e:
                      \rxData$next [94] = debouncedRx;
                  8'h5f:
                      \rxData$next [95] = debouncedRx;
                  8'h60:
                      \rxData$next [96] = debouncedRx;
                  8'h61:
                      \rxData$next [97] = debouncedRx;
                  8'h62:
                      \rxData$next [98] = debouncedRx;
                  8'h63:
                      \rxData$next [99] = debouncedRx;
                  8'h64:
                      \rxData$next [100] = debouncedRx;
                  8'h65:
                      \rxData$next [101] = debouncedRx;
                  8'h66:
                      \rxData$next [102] = debouncedRx;
                  8'h67:
                      \rxData$next [103] = debouncedRx;
                  8'h68:
                      \rxData$next [104] = debouncedRx;
                  8'h69:
                      \rxData$next [105] = debouncedRx;
                  8'h6a:
                      \rxData$next [106] = debouncedRx;
                  8'h6b:
                      \rxData$next [107] = debouncedRx;
                  8'h6c:
                      \rxData$next [108] = debouncedRx;
                  8'h6d:
                      \rxData$next [109] = debouncedRx;
                  8'h6e:
                      \rxData$next [110] = debouncedRx;
                  8'h6f:
                      \rxData$next [111] = debouncedRx;
                  8'h70:
                      \rxData$next [112] = debouncedRx;
                  8'h71:
                      \rxData$next [113] = debouncedRx;
                  8'h72:
                      \rxData$next [114] = debouncedRx;
                  8'h73:
                      \rxData$next [115] = debouncedRx;
                  8'h74:
                      \rxData$next [116] = debouncedRx;
                  8'h75:
                      \rxData$next [117] = debouncedRx;
                  8'h76:
                      \rxData$next [118] = debouncedRx;
                  8'h77:
                      \rxData$next [119] = debouncedRx;
                  8'h78:
                      \rxData$next [120] = debouncedRx;
                  8'h79:
                      \rxData$next [121] = debouncedRx;
                  8'h7a:
                      \rxData$next [122] = debouncedRx;
                  8'h7b:
                      \rxData$next [123] = debouncedRx;
                  8'h7c:
                      \rxData$next [124] = debouncedRx;
                  8'h7d:
                      \rxData$next [125] = debouncedRx;
                  8'h7e:
                      \rxData$next [126] = debouncedRx;
                  8'h7f:
                      \rxData$next [127] = debouncedRx;
                  8'h??:
                      \$156  = debouncedRx;
                endcase
          endcase
    endcase
    (* src = "C:\\Users\\voids\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \rxData$next  = 128'h00000000000000000000000000000000;
    endcase
  end
  assign \$7  = \$8 ;
  assign \$16  = \$17 ;
  assign \$45  = \$46 ;
  assign \$118  = \$119 ;
  assign \$145  = \$146 ;
  assign \$1  = rx;
  assign \$56  = rxState;
  assign \$74  = debouncedRx;
  assign \$80  = rxState;
  assign \$94  = rxState;
  assign \$108  = rxState;
  assign \$129  = debouncedRx;
  assign \$135  = rxState;
  assign \$148  = rxState;
  assign \$157  = rxState;
endmodule
